// Generated by gencpp from file topic_pkg/Test.msg
// DO NOT EDIT!


#ifndef TOPIC_PKG_MESSAGE_TEST_H
#define TOPIC_PKG_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <topic_pkg/TestRequest.h>
#include <topic_pkg/TestResponse.h>


namespace topic_pkg
{

struct Test
{

typedef TestRequest Request;
typedef TestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Test
} // namespace topic_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topic_pkg::Test > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::topic_pkg::Test&) { return value(); }
};

template<>
struct DataType< ::topic_pkg::Test > {
  static const char* value()
  {
    return "topic_pkg/Test";
  }

  static const char* value(const ::topic_pkg::Test&) { return value(); }
};


// service_traits::MD5Sum< ::topic_pkg::TestRequest> should match
// service_traits::MD5Sum< ::topic_pkg::Test >
template<>
struct MD5Sum< ::topic_pkg::TestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topic_pkg::Test >::value();
  }
  static const char* value(const ::topic_pkg::TestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_pkg::TestRequest> should match
// service_traits::DataType< ::topic_pkg::Test >
template<>
struct DataType< ::topic_pkg::TestRequest>
{
  static const char* value()
  {
    return DataType< ::topic_pkg::Test >::value();
  }
  static const char* value(const ::topic_pkg::TestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topic_pkg::TestResponse> should match
// service_traits::MD5Sum< ::topic_pkg::Test >
template<>
struct MD5Sum< ::topic_pkg::TestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topic_pkg::Test >::value();
  }
  static const char* value(const ::topic_pkg::TestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_pkg::TestResponse> should match
// service_traits::DataType< ::topic_pkg::Test >
template<>
struct DataType< ::topic_pkg::TestResponse>
{
  static const char* value()
  {
    return DataType< ::topic_pkg::Test >::value();
  }
  static const char* value(const ::topic_pkg::TestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPIC_PKG_MESSAGE_TEST_H
